// Generated by CoffeeScript 1.4.0
(function() {
  var client, dgram, helpers, message;

  dgram = require('dgram');

  helpers = require('helpers');

  message = new Buffer(JSON.stringify({
    graph: 'heapUsed',
    maxlen: 20
  }));

  client = dgram.createSocket("udp4");

  client.send(message, 0, message.length, 41234, "localhost", function(err, bytes) {
    return client.close();
  });

}).call(this);
