// Generated by CoffeeScript 1.4.0
(function() {
  var booyah, dgram, helpers, last, randomWalk, send;

  dgram = require('dgram');

  helpers = require('helpers');

  send = function(n) {
    var client, message;
    message = new Buffer(JSON.stringify({
      stream: 'blax',
      value: n
    }));
    client = dgram.createSocket("udp4");
    return client.send(message, 0, message.length, 41234, "localhost", function(err, bytes) {
      return client.close();
    });
  };

  randomWalk = function(last) {
    if (!last) {
      last = 0;
    }
    return last + helpers.randrange(10) - 5 + ((10 - last) / 20);
  };

  last = 0;

  booyah = function() {
    send(last = randomWalk(last));
    return setTimeout(booyah, 30);
  };

  booyah();

}).call(this);
